version: '3.8'

services:
  trojan-panel-backend:
    image: zzsolo/trojan-panel-backend:latest
    container_name: trojan-panel-backend
    ports:
      - "8080:8080"
    environment:
      - host=${MYSQL_HOST}
      - port=${MYSQL_PORT}
      - user=${MYSQL_USER}
      - password=${MYSQL_PASSWORD}
      - redisHost=${REDIS_HOST}
      - redisPort=${REDIS_PORT}
      - redisPassword=${REDIS_PASSWORD}
      - serverPort=8080
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - trojan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/account/getAccountInfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    container_name: trojan-panel-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=trojan_panel_db
      - TZ=Asia/Shanghai
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./trojan_panel_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trojan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: trojan-panel-redis
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - trojan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  mysql_data:
  redis_data:

networks:
  trojan-network:
    driver: bridge