# 工作流的名称
name: Build and Push Trojan Panel Main to Docker Hub

# 触发工作流的事件
on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # 允许手动触发

# 工作流执行的任务
jobs:
  build-and-push:
    # 任务运行的虚拟环境
    runs-on: ubuntu-latest

    # 任务包含的步骤
    steps:
      # 第1步：检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第2步：设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # 第3步：安装 garble（代码混淆工具）
      - name: Install garble
        run: go install mvdan.cc/garble@v0.10.1

      # 第4步：设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 第5步：登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 第6步：提取元数据（标签等）
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: zzsolo/trojan-panel-main
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      # 第7步：构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.optimized
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 第8步：输出镜像信息
      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}